In [2]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [3]:

df = pd.read_csv("../data/data_with_splits.csv")

In [4]:
mask = (df["diagnostic"]=="MEL")|(df["diagnostic"]=="BCC")|(df["diagnostic"]=="SCC")
df.loc[mask, "Class"] = True
df["Class"] = df["Class"].fillna(False)
df

/var/folders/87/qzvtc2dx2w77nz432trj5d780000gn/T/ipykernel_13959/3352817809.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Class"] = df["Class"].fillna(False)

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,...,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed,group_id,Class
0,0,802,891,PAT_934,1778,False,False,POMERANIA,POMERANIA,68,...,False,UNK,False,UNK,False,False,PAT_934_1778_140.png,True,e,True
1,1,93,95,PAT_430,848,False,False,GERMANY,GERMANY,75,...,True,True,False,False,True,True,PAT_430_848_476.png,True,b,True
2,2,1469,1599,PAT_459,892,False,True,GERMANY,GERMANY,84,...,True,True,True,False,True,True,PAT_459_892_804.png,True,c,True
3,3,947,1039,PAT_753,1833,False,False,GERMANY,GERMANY,59,...,True,False,False,False,False,False,PAT_753_1833_710.png,False,b,False
4,4,1408,1537,PAT_320,681,False,True,ITALY,GERMANY,70,...,False,True,False,True,False,False,PAT_320_681_724.png,True,c,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2098,2098,443,465,PAT_999,20,NaN,NaN,NaN,NaN,40,...,True,False,False,False,True,False,PAT_999_20_540.png,False,e,False
2099,2099,626,711,PAT_2006,4123,NaN,NaN,NaN,NaN,17,...,False,True,False,False,False,True,PAT_2006_4123_719.png,False,a,False
2100,2100,1863,2007,PAT_383,777,False,False,GERMANY,GERMANY,73,...,True,UNK,False,UNK,False,True,PAT_383_777_129.png,True,e,True
2101,2101,1330,1454,PAT_202,307,False,False,ITALY,UNK,77,...,True,True,False,False,True,True,PAT_202_307_927.png,True,b,True
2102,2102,2055,2224,PAT_695,1314,False,False,GERMANY,ITALY,54,...,True,UNK,True,UNK,True,True,PAT_695_1314_822.png,True,b,True

In [5]:
#X = df["Class"]
#Y = df["Border"]
features = pd.read_csv("../data/extracted_features.csv")

In [8]:
features["Class"] = df["Class"]
features

,patient_id,lesion_id,Asymmetry,Compactness,Convexity,Multicolor,Hue_Var,Sat_Var,Val_Var,Class
filename,,,,,,,,,,
PAT_431_850_472.png,PAT_431,850,0.19834,10.029848,0.894840,70.048865,0.000487,0.013029,0.012622,True
PAT_1468_1622_219.png,PAT_1468,1622,0.31130,13.983677,0.838614,42.320748,0.003520,0.013476,0.004512,False
PAT_759_1433_973.png,PAT_759,1433,0.09698,8.204131,0.972883,70.167322,0.136026,0.007100,0.004742,False
PAT_1031_148_66.png,PAT_1031,148,0.64280,17.893819,0.598991,26.685451,0.010076,0.002207,0.002820,False
PAT_355_732_102.png,PAT_355,732,0.23648,9.356164,0.982207,104.930983,0.002819,0.012866,0.002568,True
...,...,...,...,...,...,...,...,...,...,...
PAT_245_376_197.png,PAT_245,376,0.60698,25.678562,0.554037,89.007152,0.000084,0.000430,0.004920,True
PAT_572_1086_130.png,PAT_572,1086,0.22284,14.063679,0.877016,65.539349,0.031496,0.007352,0.004415,True
PAT_1350_1230_878.png,PAT_1350,1230,0.08786,8.624302,0.965330,60.013800,0.018407,0.014666,0.007933,False
PAT_1407_1402_500.png,PAT_1407,1402,0.72306,20.399062,0.387141,104.590799,0.006956,0.006672,0.006200,False
PAT_2048_4333_63.png,PAT_2048,4333,0.13616,9.521869,0.965200,72.057483,0.001173,0.006415,0.004367,False