In [1]:
import pandas as pd

In [3]:
df= pd.read_csv("../data/extracted_features_baseline.csv")

In [5]:
df

,patient_id,lesion_id,filename,Asymmetry,Compactness,Convexity,Multicolor,red_pixels,blue_pixels,mean_red,mean_blue,Entropy,Hue_Var,Sat_Var,Val_Var,group_id,2_3_lesions,Class
0,PAT_431,850,PAT_431_850_472.png,0.19834,10.029848,0.894840,152.580876,99.844828,0.000000,145.604310,35.178276,0.777937,0.000487,0.013029,0.012622,d,False,True
1,PAT_759,1433,PAT_759_1433_973.png,0.09698,8.204131,0.972883,123.456674,57.137228,12.816471,145.485075,130.973796,2.234851,0.136026,0.007100,0.004742,e,False,True
2,PAT_86,1109,PAT_86_1109_306.png,0.24752,10.064621,0.951783,96.192891,93.669339,0.000000,205.528981,170.086369,1.396115,0.022172,0.005550,0.004305,b,False,True
3,PAT_355,732,PAT_355_732_102.png,0.23648,9.356164,0.982207,106.893328,99.975079,0.000000,190.510191,86.976004,0.784037,0.002819,0.012866,0.002568,c,False,False
4,PAT_365,751,PAT_365_751_709.png,0.15144,10.755980,0.987811,75.423840,99.984932,0.000000,169.460490,88.883832,0.584995,0.001047,0.005928,0.001955,d,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,PAT_2017,4164,PAT_2017_4164_500.png,0.14456,9.970740,0.952108,102.417758,100.000000,0.000000,161.390840,90.278091,0.708318,0.002242,0.017533,0.007068,c,False,False
1730,PAT_572,1086,PAT_572_1086_130.png,0.22284,14.063679,0.877016,68.625142,93.088893,0.022527,111.377336,78.740256,1.525614,0.031496,0.007352,0.004415,b,False,True
1731,PAT_2048,4333,PAT_2048_4333_63.png,0.13616,9.521869,0.965200,80.346978,100.000000,0.000000,181.195859,110.550536,0.461163,0.001173,0.006415,0.004367,d,False,True
1732,PAT_253,384,PAT_253_384_607.png,0.07566,8.573423,0.992025,76.986016,100.000000,0.000000,189.304487,132.414000,0.410630,0.001475,0.005050,0.002678,a,False,True
1733,PAT_827,1598,PAT_827_1598_85.png,0.22318,11.461160,0.912088,68.741556,99.931871,0.000000,135.725744,65.864798,0.614122,0.003687,0.006877,0.003349,a,False,False

In [ ]:
df[df["filename"]=="PAT_86_131_107.png"]
#symmetrical

,patient_id,lesion_id,filename,Asymmetry,Compactness,Convexity,Multicolor,red_pixels,blue_pixels,mean_red,mean_blue,Entropy,Hue_Var,Sat_Var,Val_Var,group_id,2_3_lesions,Class
608,PAT_86,131,PAT_86_131_107.png,0.27282,15.516634,0.811041,138.999794,52.330522,13.260194,124.68335,114.022259,2.749724,0.098935,0.000643,0.004076,c,False,False

In [ ]:
df[df["filename"]=="PAT_191_294_629.png"]
#asymmetrical

,patient_id,lesion_id,filename,Asymmetry,Compactness,Convexity,Multicolor,red_pixels,blue_pixels,mean_red,mean_blue,Entropy,Hue_Var,Sat_Var,Val_Var,group_id,2_3_lesions,Class
384,PAT_191,294,PAT_191_294_629.png,0.47018,23.396186,0.778198,188.804682,82.571195,6.63282,109.759069,75.795518,1.941768,0.079967,0.020537,0.016692,c,False,True

In [ ]:
df[df["filename"]=="PAT_79_120_739.png"]
#

,patient_id,lesion_id,filename,Asymmetry,Compactness,Convexity,Multicolor,red_pixels,blue_pixels,mean_red,mean_blue,Entropy,Hue_Var,Sat_Var,Val_Var,group_id,2_3_lesions,Class
979,PAT_79,120,PAT_79_120_739.png,0.2844,14.664987,0.795229,35.384593,100.0,0.0,149.407291,74.979246,0.252255,0.000492,0.000664,0.000122,b,False,True